#!/usr/bin/env python3

import tkinter as tk
from PIL import Image, ImageTk

root = tk.Tk()

frame = tk.Frame(root)
frame.grid()

canvas = tk.Canvas(root, height=480, width=720)
img = Image.open("1.jpg")
photo = ImageTk.PhotoImage(img)
img = canvas.create_image(0, 0, anchor="nw", image=photo)
canvas.grid(row=1, column=1)

root.mainloop()
