#!/usr/bin/env python3

import copy
import tkinter.filedialog as fd
import tkinter as Tk
from PIL import Image, ImageTk

class RGB:
	RED = 0
	GREEN = 1
	BLUE = 2
	COLORS = [RED, GREEN, BLUE]
	LUMS = [0.3, 0.59, 0.11]
	MAXVAL = 255

	def Lum(px):
		v = 0
		i = 0
		for l in LUMS :
			v += px[i] * l
			i += 1
		return v

class App:
	CursorBorderWidth = 5
	IntensifyVal = 5
	ModKey = "<Control-%s>"
	def __init__(self):
		self.Root = Tk.Tk()
		self.Root.bind("n", self.loadNewImage)
		self.Root.bind(self.ModKey % "n",
			lambda a: self.negativeColor())
		self.Root.bind("r",
			lambda a: self.intensifyColor([RGB.RED], self.IntensifyVal))
		self.Root.bind(self.ModKey % "r",
			lambda a: self.intensifyColor([RGB.RED], -self.IntensifyVal))
		self.Root.bind("g",
			lambda a: self.intensifyColor([RGB.GREEN], self.IntensifyVal))
		self.Root.bind(self.ModKey % "g",
			lambda a: self.intensifyColor([RGB.GREEN], -self.IntensifyVal))
		self.Root.bind("b",
			lambda a: self.intensifyColor([RGB.BLUE], self.IntensifyVal))
		self.Root.bind(self.ModKey % "b",
			lambda a: self.intensifyColor([RGB.BLUE], -self.IntensifyVal))
		self.Root.bind("l",
			lambda a: self.intensifyColor(RGB.COLORS, self.IntensifyVal))
		self.Root.bind(self.ModKey % "l",
			lambda a: self.intensifyColor(RGB.COLORS, -self.IntensifyVal))

		# Define main variables.
		self.Image = None
		self.Photo = None
		self.RGB = None
		self.Canvas = None

		self.loadNewImage()

	def Start(self):
		self.Root.mainloop()

	def intensifyColor(self, colors, val):
		s = list(self.Image.split())
		for c in colors :
			s[c] = s[c].point(lambda i: i + val)
		self.Image = Image.merge("RGB", tuple(s))
		self.updateImage(self.Image)

	def negativeColor(self):
		s = list(self.Image.split())
		for c in RGB.COLORS :
			s[c] = s[c].point(lambda v: RGB.MAXVAL - v)
		self.Image = Image.merge("RGB", tuple(s))
		self.updateImage(self.Image)

	def drawCursorBorder(self, ev):
		cw = self.CursorBorderWidth
		self.Canvas.create_line(
			ev.x-cw,
			ev.y-cw,
			ev.x+cw,
			ev.y-cw,
			tag="top"
		)

		self.Canvas.create_line(
			ev.x-cw,
			ev.y-cw,
			ev.x-cw,
			ev.y+cw,
			tag="left"
		)

		self.Canvas.create_line(
			ev.x+cw,
			ev.y-cw,
			ev.x+cw,
			ev.y+cw,
			tag="right"
		)

		self.Canvas.create_line(
			ev.x - cw,
			ev.y + cw,
			ev.x + cw,
			ev.y + cw,
			tag="bottom"
		)

	def onCanvasMouseMotion(self, ev):
		px = self.Image.getpixel((ev.x, ev.y))
		self.Root.title(
			"x:%d y:%d #%x%x%x Intensity:%d%%" \
				% (
					ev.x, ev.y,
					px[0], px[1], px[2],
					int((px[0]+px[1]+px[2])/3/256 * 100)
			)
		)
		for i in ["top", "left", "right", "bottom"] :
			self.Canvas.delete(i)
		self.drawCursorBorder(ev)


	def updateImage(self, img):
		self.Photo = ImageTk.PhotoImage(img)
		self.CanvasImage = self.Canvas.create_image(0, 0, anchor="nw", image=self.Photo)

	def loadNewImage(self, *args):
		path = fd.askopenfilename()
		self.Image = Image.open(path).convert("RGB")
		# self.RGB = self.Image.convert("RGB")

		self.Canvas = Tk.Canvas(
			self.Root,
			width=self.Image.size[0],
			height=self.Image.size[1]
		)

		self.updateImage(self.Image)
		self.Canvas.place(relx=0.5, rely=0.5, anchor=Tk.CENTER)

		self.Canvas.bind("<Motion>", self.onCanvasMouseMotion)

class Histogram:
	def __init__(self, app):
		self.Master = app.Root
		self.Root = Tk.Toplevel(self.Master)
		self.Root.geometry("200x200")


app = App()
app.Start()
hist = Histogram(app)

